spring:
  application:
    name: sportswear-be
  data:
    mongodb:
      uri: mongodb+srv://NVD-NVD:1gVDdiq1RKs2LVh2@cluster0.7hkjpog.mongodb.net/?retryWrites=true&w=majority
#      host: localhost
#      port: 27017
      database: sportswear-database
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh

jwt:
  secret: K1LqzK6eeD0g0BfgOg7S

default:
  token_type: "Bearer"
  password: 12345678
  avatar: "default.png"
  updatingInfoBook: "Đang cập nhập"

mail:
  MyConstants:
    MY_EMAIL: "zerodev247@gmail.com"
    MY_PASSWORD: "buzylnegzpqswgkk"

host: "https://sportswear-be.herokuapp.com/rest/"

upload:
  url: "https://sportswear-be.herokuapp.com/"
  path: "/uploads/"

cloudinary:
  cloud_name: dw0tkzfyp
  api_key: 731957348138624
  api_secret: hlYPsGMbQnDbgYbFb9BpM0SFwUs

paging:
  default:
    page: 0
    size: 20
google:
  verifyUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=

logging:
  level:
    org.springframework.cache: error
  file:
    name: logs/sportswear-be.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7

server:
  error:
    include-exception: true
    include-message: always
  port: 8080